### ISSUE TITLE
Move to ITRB

### ISSUE THREAD

**Issue by cbizon** [di2ag/Connections-Hypothesis-Provider-Roadmap#88]
![image](https://user-images.githubusercontent.com/10744350/183753674-772f8bfc-4b10-419e-8546-efe5abd521f6.png)

* Prod needs to move to ITRB asap
* Testing and staging also need to be in ITRB soon
* The x-maturity level should be 'development' instead of 'dev'

**Comment by tursynay** [comment]
@veenhouse, would you be the right person to assign this issue to?

**Comment by veenhouse** [comment]
Sorry for the delayed update, have been coordinating with ITRB on finalizing our transition. Progress is well under way, we are currently working on the final development towards fully integrating our service into ITRB's infrastructure. Just waiting on the data ingestion pipeline to be finished so that we can integrate with ITRB's database. We expect this to be the last update needed before we change our endpoints on our SmartAPI registration. If all goes to plan I would anticipate finishing by week's end.
